In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
myarray = np.array(mylist)

In [6]:
type(myarray)

numpy.ndarray

In [8]:
myarray

array([1, 2, 3])

In [9]:
my_matrix = [[1,2,3],[4,5,6], [7,8,9]]

In [10]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
np.zeros((5, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [20]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.random.rand(1)

array([0.79357853])

In [23]:
np.random.rand(5,6)

array([[0.10759412, 0.81169823, 0.0730313 , 0.75874011, 0.95056845,
        0.01491725],
       [0.03846379, 0.44294263, 0.24097243, 0.78708275, 0.0221558 ,
        0.7085324 ],
       [0.90521284, 0.29554099, 0.72303713, 0.50728299, 0.08288187,
        0.66511196],
       [0.9293674 , 0.79116759, 0.83187725, 0.09372736, 0.44737546,
        0.22407323],
       [0.10851828, 0.32427155, 0.54438539, 0.74032583, 0.62163391,
        0.20258589]])

In [24]:
np.random.randn(10)

array([-0.77053586, -0.88838544, -0.73285937, -0.48674431,  0.32027537,
       -0.20407436, -0.10144903,  0.11773956,  0.05950069,  1.1814995 ])

In [25]:
np.random.randn(10,3)

array([[-0.39636342,  0.50800599, -0.33382853],
       [-1.4334253 , -0.05593527,  0.24926908],
       [-0.03343358, -0.44537511,  1.79480058],
       [-2.07833434, -0.32696521,  0.35114157],
       [-0.31357148,  0.32010674,  1.5295776 ],
       [-0.28297625, -0.15143291, -0.7499085 ],
       [ 0.45073792,  0.97579876,  0.88408845],
       [-0.03149369, -0.90180527,  0.8516607 ],
       [ 1.02041334, -0.77402633,  1.08177307],
       [ 0.22800336, -0.44589901, -1.10946222]])

In [26]:
np.random.randint(0,101, 5)

array([91, 83,  9, 24,  2])

In [28]:
np.random.randint(0,101, (5,2))

array([[68, 16],
       [71,  7],
       [62, 16],
       [40,  6],
       [ 5, 52]])

In [30]:
np.random.seed(42)

np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [31]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [34]:
ranarr = np.random.randint(0, 101, 10)

In [35]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [36]:
ranarr.max()

99

In [37]:
ranarr.min()

2

In [38]:
# " index location of elementts -> arg"
ranarr.argmax()

5

In [39]:
ranarr.argmin()

7

In [40]:
ranarr.dtype

dtype('int32')

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
arr.shape

(25,)

In [43]:
arr = arr.reshape(5,5)

In [44]:
arr.shape

(5, 5)

In [45]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [46]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [47]:
arr.reshape(25,)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])